=== ivangre4/PLC_Programms/Programms_Siemens/Step7/S7DATA/S7AMPAS/s7ampas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) Siemens AG 2002. All Rights Reserved. Confidential. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Step">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Resource" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Position">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Tree"/>
									<xs:enumeration value="Title"/>
									<xs:enumeration value="Description"/>
									<xs:enumeration value="Error"/>
									<xs:enumeration value="Success"/>
									<xs:enumeration value="NothingToDo"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ResourcePath" type="xs:string"/>
						<xs:attribute name="ID" type="xs:long"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Relation" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="SourceType" type="xs:long"/>
						<xs:attribute name="RelID" type="xs:long"/>
						<xs:attribute name="TargetType" type="xs:long"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ID" type="xs:long" use="required"/>
			<xs:attribute name="ParentID" type="xs:long" use="optional" default="0"/>
			<xs:attribute name="ObjType" type="xs:long" use="optional" default="0"/>
			<xs:attribute name="TypeVerb" type="xs:long" use="optional" default="0"/>
			<xs:attribute name="ResourcePath" type="xs:string use="optional"/>
			<xs:attribute name="HelpPath" type="xs:string use="optional"/>
			<xs:attribute name="HelpID" type="xs:long" use="optional" default="0"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Step" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ResourcePath" type="xs:string" use="optional"/>
			<xs:attribute name="HelpPath" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>
<!-- Copyright (C) Siemens AG 2002. All Rights Reserved. Confidential. -->

=== ivangre4/PLC_Programms/Programms_Siemens/Step7/S7DATA/S7AMPAS/s7mpbase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) Siemens AG 2002. All Rights Reserved. Confidential. -->
<Steps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s7ampas.xsd" ResourcePath="s7ampas">
	<!-- Subnetze zusammenführen / trennen -->
	<Step ID="1000">
		<Resource Position="Tree" ID="3"/>
		<Resource Position="Title" ID="3"/>
		<Resource Position="Description" ID="15"/>
	</Step>
	<!-- Ethernet-Subnetze zusammenführen / trennen -->
	<Step ID="1100" ParentID="1000" ObjType="1331459" TypeVerb="43966">
		<Resource Position="Tree" ID="6"/>
		<Resource Position="Title" ID="9"/>
		<Resource Position="Description" ID="12"/>
	</Step>
	<!-- MPI-Subnetze zusammenführen / trennen -->
	<Step ID="1200" ParentID="1000" ObjType="1331457" TypeVerb="43966">
		<Resource Position="Tree" ID="4"/>
		<Resource Position="Title" ID="7"/>
		<Resource Position="Description" ID="10"/>
	</Step>
	<!-- PROFIBUS-Subnetze zusammenführen / trennen -->
	<Step ID="1300" ParentID="1000" ObjType="1331458" TypeVerb="43966">
		<Resource Position="Tree" ID="5"/>
		<Resource Position="Title" ID="8"/>
		<Resource Position="Description" ID="11"/>
	</Step>
	<!-- Verbindungen zusammenführen -->
	<Step ID="2000" ObjType="1122320" TypeVerb="8196">
		<Resource Position="Tree" ID="2"/>
		<Resource Position="Title" ID="2"/>
		<Resource Position="Description" ID="1"/>
		<Resource Position="Error" ID="16"/>
		<Resource Position="Success" ID="17"/>
		<Resource Position="NothingToDo" ID="18"/>
		<Relation SourceType="12" RelID="205" TargetType="12"/>
	</Step>
</Steps>
<!-- Copyright (C) Siemens AG 2002. All Rights Reserved. Confidential. -->
