=== ivangre4/PLC_Programms/Programms_Siemens/Step7/S7DATA/snmp/snmp_ini/s7snmpalarm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Dietmar Kern (Siemens AG) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SNMP_Alarms">
		<xs:annotation>
			<xs:documentation>SNMP alarm mapping configuration.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DeviceType" type="TypeDeviceType" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The list of SNMP alarm device types.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="AlarmText" type="TypeAlarmText" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The multilingual alarm message texts.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="DefaultDeviceType" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Name of the default device type.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="TypeTextMax64">
		<xs:annotation>
			<xs:documentation>Text which is up to MSG_MAX_TEXTLEN (64) characters long.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="64"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TypeTextMax127">
		<xs:annotation>
			<xs:documentation>Text which is up to MAX_DM_VAR_NAME - 1 (127) characters long.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="127"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TypeTextMax254">
		<xs:annotation>
			<xs:documentation>Text which is up to MSG_MAX_TB_CONTENT - 1 (254) characters long.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="254"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TypeTextMax255">
		<xs:annotation>
			<xs:documentation>Text which is up to MSG_MAX_TB_CONTENT (255) characters long.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TypeLanguage">
		<xs:annotation>
			<xs:documentation>Enumeration of windows main language identifiers.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="4"/>                                  ;Not used in PCS7  
			<xs:enumeration value="7"/>                               	;German
			<xs:enumeration value="9"/>  								;English
			<xs:enumeration value="10"/>								;Spanish
			<xs:enumeration value="12"/>								;French
			<xs:enumeration value="16"/>								;Italian
			<xs:enumeration value="17"/>								;Not used in PCS7  
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="TypeBitVar">
		<xs:annotation>
			<xs:documentation>A variable with a significant bit. The bit with the specified bitnumber will trigger events on change.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="xs:anyType">
				<xs:sequence>
					<xs:element name="Name" type="TypeTextMax127">
						<xs:annotation>
							<xs:documentation>The variable name.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="Bit" use="optional" default="0">
					<xs:annotation>
						<xs:documentation>The significant bit.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:annotation>
								<xs:documentation>WORD.</xs:documentation>
							</xs:annotation>
							<xs:minInclusive value="0"/>
							<xs:maxExclusive value="65536"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TypeAction">
		<xs:annotation>
			<xs:documentation>Configuration data of actions for this message.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="xs:anyType">
				<xs:sequence>
					<xs:element name="Name" type="TypeTextMax255" default="OpenPicture" minOccurs="0">
						<xs:annotation>
							<xs:documentation>The function name of this action.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Param" type="TypeTextMax255" minOccurs="0">
						<xs:annotation>
							<xs:documentation>The parameters for the function call.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="Type" use="optional" default="0">
					<xs:annotation>
						<xs:documentation>Type of action.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:annotation>
								<xs:documentation>DWORD.</xs:documentation>
							</xs:annotation>
							<xs:minInclusive value="0"/>
							<xs:maxExclusive value="4294967296"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TypeAlarmMessage">
		<xs:annotation>
			<xs:documentation>An alarm message configuration.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="xs:anyType">
				<xs:sequence>
					<xs:element name="InfoText" type="TypeTextMax254" minOccurs="0">
						<xs:annotation>
							<xs:documentation>A help text.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="MsgVar" type="TypeBitVar">
						<xs:annotation>
							<xs:documentation>Triggers alarms.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="QuitVar" type="TypeBitVar" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Quit variable.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="StateVar" type="TypeBitVar" minOccurs="0">
						<xs:annotation>
							<xs:documentation>State variable.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ProcessValue" type="TypeTextMax127" minOccurs="0" maxOccurs="10">
						<xs:annotation>
							<xs:documentation>Process values. Needed if the alarm text is formatted to show the values of tags at runtime.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="GroupName" type="TypeTextMax64" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Name of alarm group.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="NormDll" type="TypeTextMax64" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Filename of norm dll.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Action" type="TypeAction" minOccurs="0">
						<xs:annotation>
							<xs:documentation>The action for an SNMP message (normally: loop in alarm).</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TextOrigin" type="TypeTextRef">
						<xs:annotation>
							<xs:documentation>Alarm source: the SNMP device name.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TextArea" type="TypeTextRef" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Alarm area: diagnosis.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TextEvent" type="TypeTextRef" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Alarm event text.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TextCharge" type="TypeTextRef" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Charge text.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TextOperation" type="TypeTextRef" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Operation text.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TextFree" type="TypeTextRef" minOccurs="0" maxOccurs="5">
						<xs:annotation>
							<xs:documentation>Arbitrary additional texts.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="Priority" use="optional" default="0">
					<xs:annotation>
						<xs:documentation>Alarm priority. 0 is lowest, 16 ist highest priority.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="16"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="Class" use="optional" default="NO_ALARM_CLASS">
					<xs:annotation>
						<xs:documentation>Alarm message class.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="NO_ALARM_CLASS"/>
							<xs:enumeration value="ALARM"/>
							<xs:enumeration value="WARNING"/>
							<xs:enumeration value="TOLERANCE"/>
							<xs:enumeration value="PCS1_PLC"/>
							<xs:enumeration value="PCS2_OS"/>
							<xs:enumeration value="PCS3_MAINTANCE"/>
							<xs:enumeration value="PROCESSMESSAGE"/>
							<xs:enumeration value="PROCESSMESSAGE2"/>
							<xs:enumeration value="OPARATORINPUTREQUEST"/>
							<xs:enumeration value="OPARATIONMESSAGE"/>
							<xs:enumeration value="STATUS"/>
							<xs:enumeration value="DEFAULT1"/>
							<xs:enumeration value="DEFAULT2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="Type" use="optional" default="NO_ALARM_TYPE">
					<xs:annotation>
						<xs:documentation>Alarm message type.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="NO_ALARM_TYPE"/>
							<xs:enumeration value="ALARMHIGH"/>
							<xs:enumeration value="ALARMLOW"/>
							<xs:enumeration value="WARNINGHIGH"/>
							<xs:enumeration value="WARNINGLOW"/>
							<xs:enumeration value="TOLERANCEHIGH"/>
							<xs:enumeration value="TOLERANCELOW"/>
							<xs:enumeration value="PCS_TROUBLE"/>
							<xs:enumeration value="PCS_ERROR"/>
							<xs:enumeration value="PCS_MAINTANCE"/>
							<xs:enumeration value="PROCESSMESSAGE"/>
							<xs:enumeration value="OPARATORINPUTREQUEST"/>
							<xs:enumeration value="OPARATIONMESSAGE"/>
							<xs:enumeration value="STATUS_AS"/>
							<xs:enumeration value="STATUS_OS"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="StatusHorn" type="xs:boolean" use="optional" default="true">
					<xs:annotation>
						<xs:documentation>If true then message activates horn.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="StatusArchive" type="xs:boolean" use="optional" default="true">
					<xs:annotation>
						<xs:documentation>If true then message will be stored in an archive.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="StatusProtocol" type="xs:boolean" use="optional" default="true">
					<xs:annotation>
						<xs:documentation>If true then message will be included in a report.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="StatusAPFunc" type="xs:boolean" use="optional" default="false">
					<xs:annotation>
						<xs:documentation>If true then message will control a global AP function.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="StatusVarFlank" type="xs:boolean" use="optional" default="false">
					<xs:annotation>
						<xs:documentation>If true then message will be created on a negative edge of the alarm tag.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="StatusSQuit" type="xs:boolean" use="optional" default="false">
					<xs:annotation>
						<xs:documentation>If true then message will require individual acknowledgement.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="StatusLocked" type="xs:boolean" use="optional" default="false">
					<xs:annotation>
						<xs:documentation>If true then message be locked during startup.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TypeTextRef">
		<xs:annotation>
			<xs:documentation>A reference to an alarm text.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="xs:anyType">
				<xs:attribute name="TextRef" type="xs:positiveInteger">
					<xs:annotation>
						<xs:documentation>The id of the alarm text.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TypeAlarmText" mixed="true">
		<xs:annotation>
			<xs:documentation>A multilingual alarm text. Contains zero or more localized alarm texts.</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:restriction base="xs:anyType">
				<xs:sequence>
					<xs:element name="LocalizedText" type="TypeLocalizedText" minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>The list of localized texts.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="Id" type="xs:ID" use="required">
					<xs:annotation>
						<xs:documentation>The id of the message text (unique).</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TypeLocalizedText" mixed="true">
		<xs:annotation>
			<xs:documentation>A localized alarm text.</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:restriction base="xs:anyType">
				<xs:attribute name="LanguageId" type="TypeLanguage" use="required">
					<xs:annotation>
						<xs:documentation>The language id as a windows main language identifier.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TypeDeviceType">
		<xs:annotation>
			<xs:documentation>A device type configuration. Contains zero or more alarm message configuration as well as the multilingual alarm texts for this device type.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="AlarmMessage" type="TypeAlarmMessage" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The alarm message templates for this device type.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:ID" use="required">
			<xs:annotation>
				<xs:documentation>The device name (unique).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== ivangre4/PLC_Programms/Programms_Siemens/Step7/S7DATA/snmp/snmp_ini/s7snmpalarm.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Samrat (Siemens AG) -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Hr. Vogt (Siemens AG) -->
<SNMP_Alarms DefaultDeviceType="SNMP_DEFAULT" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./s7snmpalarm.xsd">
	<DeviceType Name="SNMP_SWITCH">
		<AlarmMessage Class="PCS1_PLC" Type="PCS_TROUBLE">
			<InfoText>Switch is in a fault state. Indicates OSM/ESM fault state
			</InfoText>
			<MsgVar Bit="1">
				<Name>snOsmfaultstate</Name>
			</MsgVar>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<Action>
				<Name>LoopInAlarm</Name>
				<Param>Dummy</Param>
			</Action>
			<TextOrigin TextRef="1"/>
			<TextArea TextRef="2"/>
			<TextEvent TextRef="30"/>
		</AlarmMessage>
	</DeviceType>
	<DeviceType Name="SNMP_IPC">
		<AlarmMessage Class="PCS3_MAINTANCE" Type="PCS_MAINTANCE">
			<InfoText>IPC status.
			</InfoText>
			<MsgVar Bit="29">
				<Name>AlarmNotificationRegister</Name>
			</MsgVar>
			<QuitVar Bit="29">
				<Name>AlarmAcknowledgeRegister</Name>
			</QuitVar>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<Action>
				<Name>LoopInAlarm</Name>
				<Param>Dummy</Param>
			</Action>
			<TextOrigin TextRef="1"/>
			<TextArea TextRef="2"/>
			<TextEvent TextRef="22"/>
		</AlarmMessage>
		<AlarmMessage Class="PCS1_PLC" Type="PCS_ERROR">
			<InfoText>IPC status.
			</InfoText>
			<MsgVar Bit="30">
				<Name>AlarmNotificationRegister</Name>
			</MsgVar>
			<QuitVar Bit="30">
				<Name>AlarmAcknowledgeRegister</Name>
			</QuitVar>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<Action>
				<Name>LoopInAlarm</Name>
				<Param>Dummy</Param>
			</Action>
			<TextOrigin TextRef="1"/>
			<TextArea TextRef="2"/>
			<TextEvent TextRef="21"/>
		</AlarmMessage>
		<AlarmMessage Class="PCS1_PLC" Type="PCS_TROUBLE">
			<InfoText>IPC status.
			</InfoText>
			<MsgVar Bit="31">
				<Name>AlarmNotificationRegister</Name>
			</MsgVar>
			<QuitVar Bit="31">
				<Name>AlarmAcknowledgeRegister</Name>
			</QuitVar>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<Action>
				<Name>LoopInAlarm</Name>
				<Param>Dummy</Param>
			</Action>
			<TextOrigin TextRef="1"/>
			<TextArea TextRef="2"/>
			<TextEvent TextRef="20"/>
		</AlarmMessage>
	</DeviceType>
	<DeviceType Name="SNMP_DEFAULT">
		<AlarmMessage Class="PCS1_PLC" Type="PCS_TROUBLE">
			<InfoText>SNMP path status.
			</InfoText>
			<MsgVar Bit="0">
				<Name>&amp;statepathval()</Name>
			</MsgVar>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<ProcessValue/>
			<Action>
				<Name>LoopInAlarm</Name>
				<Param>Dummy</Param>
			</Action>
			<TextOrigin TextRef="1"/>
			<TextArea TextRef="2"/>
			<TextEvent TextRef="3"/>
		</AlarmMessage>
	</DeviceType>
	<AlarmText Id="TextId_1">
		<LocalizedText LanguageId="7">
			Dummy
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Dummy
		</LocalizedText>
		<LocalizedText LanguageId="16">Dummy</LocalizedText>
		<LocalizedText LanguageId="12">Dummy</LocalizedText>
		<LocalizedText LanguageId="10">Dummy</LocalizedText>
		<LocalizedText LanguageId="4">Dummy</LocalizedText>
		<LocalizedText LanguageId="17">Dummy</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_2">
		<LocalizedText LanguageId="7">
			Dummy
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Dummy
		</LocalizedText>
		<LocalizedText LanguageId="16">Dummy</LocalizedText>
		<LocalizedText LanguageId="12">Dummy</LocalizedText>
		<LocalizedText LanguageId="10">Dummy</LocalizedText>
		<LocalizedText LanguageId="4">Dummy</LocalizedText>
		<LocalizedText LanguageId="17">Dummy</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_3">
		<LocalizedText LanguageId="7">
			SNMP-Geraet ist nicht erreichbar.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			SNMP device is not answering.
		</LocalizedText>
		<LocalizedText LanguageId="16">apparecchio SNMP non aggiungibile. </LocalizedText>
		<LocalizedText LanguageId="12">L’appareil SNMP ne répond pas. </LocalizedText>
		<LocalizedText LanguageId="10">El dispositivo SNMP no responde.</LocalizedText>
		<LocalizedText LanguageId="4">SNMP设备没有应答。</LocalizedText>
		<LocalizedText LanguageId="17">SNMPデバイスの応答がありません。</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_10">
		<LocalizedText LanguageId="7">
			Alarm von Sensor 1.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Alarm from sensor 1.
		</LocalizedText>
		<LocalizedText LanguageId="16">Allarme del sensore 1.</LocalizedText>
		<LocalizedText LanguageId="12">Alarme du capteur 1.</LocalizedText>
		<LocalizedText LanguageId="10">Alarma del sensor 1.</LocalizedText>
		<LocalizedText LanguageId="4">来自传感器1的报警。</LocalizedText>
		<LocalizedText LanguageId="17">センサ1からのアラーム</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_11">
		<LocalizedText LanguageId="7">
			Alarm von sensor 2.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Alarm from sensor 2.
		</LocalizedText>
		<LocalizedText LanguageId="16">Allarme del sensore 2.</LocalizedText>
		<LocalizedText LanguageId="12">Alarme du capteur 2.</LocalizedText>
		<LocalizedText LanguageId="10">Alarma del sensor 2.</LocalizedText>
		<LocalizedText LanguageId="4">来自传感器2的报警。</LocalizedText>
		<LocalizedText LanguageId="17">センサ2からのアラーム</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_12">
		<LocalizedText LanguageId="7">
			Alarm von Sensor 3.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Alarm from sensor 3.
		</LocalizedText>
		<LocalizedText LanguageId="16">Allarme del sensore 3.</LocalizedText>
		<LocalizedText LanguageId="12">Alarme du capteur 3.</LocalizedText>
		<LocalizedText LanguageId="10">Alarma del sensor 3.</LocalizedText>
		<LocalizedText LanguageId="4">来自传感器3的报警。</LocalizedText>
		<LocalizedText LanguageId="17">センサ3からのアラーム</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_13">
		<LocalizedText LanguageId="7">
			Alarm von Sensor 4.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Alarm from sensor 4.
		</LocalizedText>
		<LocalizedText LanguageId="16">Allarme del sensore 4.</LocalizedText>
		<LocalizedText LanguageId="12">Alarme du capteur 4.</LocalizedText>
		<LocalizedText LanguageId="10">Alarma del sensor 4.</LocalizedText>
		<LocalizedText LanguageId="4">来自传感器4的报警。</LocalizedText>
		<LocalizedText LanguageId="17">センサ4からのアラーム</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_14">
		<LocalizedText LanguageId="7">
			Alarm von Sensor 5.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Alarm from sensor 5.
		</LocalizedText>
		<LocalizedText LanguageId="16">Allarme del sensore 5.</LocalizedText>
		<LocalizedText LanguageId="12">Alarme du capteur 5.</LocalizedText>
		<LocalizedText LanguageId="10">Alarma del sensor 5.</LocalizedText>
		<LocalizedText LanguageId="4">来自传感器5的报警。</LocalizedText>
		<LocalizedText LanguageId="17">センサ5からのアラーム</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_15">
		<LocalizedText LanguageId="7">
			Alarm von Sensor 6.
		</LocalizedText>
		<LocalizedText LanguageId="9">
			Alarm from sensor 6.
		</LocalizedText>
		<LocalizedText LanguageId="16">Allarme del sensore 6.</LocalizedText>
		<LocalizedText LanguageId="12">Alarme du capteur 6.</LocalizedText>
		<LocalizedText LanguageId="10">Alarma del sensor 6.</LocalizedText>
		<LocalizedText LanguageId="4">来自传感器6的报警。</LocalizedText>
		<LocalizedText LanguageId="17">センサ6からのアラーム</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_20">
		<LocalizedText LanguageId="7">
Gerät schlecht, Wartungsalarm</LocalizedText>
		<LocalizedText LanguageId="9">Device bad, Maintenance alarm. </LocalizedText>
		<LocalizedText LanguageId="16">Apparecchio difettoso, allarme di manutenzione.</LocalizedText>
		<LocalizedText LanguageId="12">Appareil dctueux, alarme de maintenance. </LocalizedText>
		<LocalizedText LanguageId="10">Dispositivo mal, alarma de mantenimiento. </LocalizedText>
		<LocalizedText LanguageId="4">设备坏，维护报警。</LocalizedText>
		<LocalizedText LanguageId="17">デバイス不良、メンテナンスアラーム。</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_21">
		<LocalizedText LanguageId="7">
Gerät unsicher, Wartungsanforderung</LocalizedText>
		<LocalizedText LanguageId="9">Device Uncertain, Maintenance Required.</LocalizedText>
		<LocalizedText LanguageId="16">Apparecchio inaffidabile, richiesta di manutenzione.</LocalizedText>
		<LocalizedText LanguageId="12">Appareil incertain, maintenance requise.</LocalizedText>
		<LocalizedText LanguageId="10">Dispositivo inseguro, requiere mantenimiento.</LocalizedText>
		<LocalizedText LanguageId="4">设备不确定，要求维护。</LocalizedText>
		<LocalizedText LanguageId="17">デバイス不明、メンテナンスが必要です。</LocalizedText>
	</AlarmText>
	<AlarmText Id="TextId_22">
		<LocalizedText LanguageId="7">
Gerät Gut, Wartungsbedarf</LocalizedText>
		<LocalizedText LanguageId="9">Device Good, Maintenance needed.</LocalizedText>
		<LocalizedText LanguageId="16">Apparecchio funzionante, manutenzione necessaria.</LocalizedText>
		<LocalizedText LanguageId="12">Appareil en ordre, maintenance requise. </LocalizedText>
		<LocalizedText LanguageId="10">Dispositivo bien, necesita mantenimiento. </LocalizedText>
		<LocalizedText LanguageId="4">设备正常，需要维护。</LocalizedText>
		<LocalizedText LanguageId="17">デバイス良好、メンテナンスが必要です。</LocalizedText>
